### ISSUE TITLE
Queries (custom, q, and kv) have option to include facets

### ISSUE THREAD

**Issue by dscape** [marklogic-community/Corona#5]

**Comment by ryangrimm** [comment]
The topic of including facet results with search results has been discussed before via email.  To summarize a long thread, my belief is that while the two are highly related, fetching them combined can be quite confusing.  Partly because facet results do not mesh with pagination of search results.  So if a developer wants the first 10 search results and the first 25 facet results, the request would have to have a start, end and limit parameter.  Limit could be changed to facetLimit or something like that, but in general this leaves an odd taste in my mouth.

In addition, facet results really only need to be generated for the first page of search results, which I feel highlights the concept that they are two different requests.

I'm happy to elaborate more if there are strong feelings otherwise.

**Comment by dscape** [comment]
Nah that's enough - I was just flaggin the item so you could follow up. If it was thought about and decided good for me.
